package eu.wohlben.qits.deployments.api;

import static io.restassured.RestAssured.given;

import io.quarkus.test.junit.QuarkusTest;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.Test;

/**
 * Writes {@code docs/openapi.yml} as a side effect of the suite, the same way the sibling services
 * do. Checking the document in is what turns an API change into a reviewable diff instead of
 * something a caller discovers at runtime.
 *
 * <p>This is a test only because {@code @QuarkusTest} is the cheapest way to stand the application
 * up and read its own {@code /platform-deployments/q/openapi}. It asserts nothing — the assertion is the diff.
 *
 * <p>The test classpath is indexed too, so any {@code @Path} resource under {@code src/test} lands
 * in the committed document unless it is {@code @Operation(hidden = true)}.
 */
@QuarkusTest
public class OpenApiSchemaExportTest {

  @Test
  public void exportOpenApiSchema() throws Exception {
    String schema = given().when().get("/platform-deployments/q/openapi").then().statusCode(200).extract().asString();

    // The module is `service/`, so this resolves to the repo root's docs/.
    Path docsDir = Paths.get("../docs");
    if (!Files.exists(docsDir)) {
      Files.createDirectories(docsDir);
    }

    String header =
        "# THIS FILE IS GENERATED BY OpenApiSchemaExportTest — DO NOT EDIT MANUALLY.\n"
            + "# Run `./mvnw -pl service -am test -Dtest=OpenApiSchemaExportTest"
            + " -Dsurefire.failIfNoSpecifiedTests=false` to regenerate.\n";

    Files.writeString(docsDir.resolve("openapi.yml"), header + schema);
  }
}
